import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { constants } from "node:fs";
import { access, chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";
import test from "node:test";
import type { AppConfig } from "../src/config.ts";
import { InMemoryRepository } from "../src/db/inMemoryRepository.ts";
import { CodexGitWorker } from "../src/workers/codexWorker.ts";

const execFileAsync = promisify(execFile);

test("CodexGitWorker claims a job, commits worker edits, and pushes to the fork", async () => {
  const temp = await mkdtemp(join(tmpdir(), "agenthub-worker-test-"));

  try {
    const remoteRoot = join(temp, "gitea");
    const bareRepo = join(remoteRoot, "agent-alpha", "demo-fork.git");
    await createBareRepoWithReadme({ bareRepo, temp });

    const fakeCodex = join(temp, "fake-codex.cjs");
    await writeFile(
      fakeCodex,
      [
        "#!/usr/bin/env node",
        'const { writeFileSync } = require("node:fs");',
        'const { join } = require("node:path");',
        "const args = process.argv.slice(2);",
        'const worktree = args[args.indexOf("--cd") + 1];',
        'const output = args[args.indexOf("--output-last-message") + 1];',
        'writeFileSync(join(worktree, "worker-added.md"), "Generated by fake Codex\\n");',
        'writeFileSync(output, "Fake Codex completed\\n");'
      ].join("\n")
    );
    await chmod(fakeCodex, 0o755);

    const repository = new InMemoryRepository();
    const agent = await repository.upsertAgent({
      id: "agt_1",
      username: "agent-alpha",
      tokenHash: "hash",
      giteaUsername: "agent-alpha"
    });
    const project = await repository.createProject({
      id: "prj_1",
      name: "Demo",
      slug: "demo",
      rootOwner: "agenthub",
      rootRepo: "demo",
      createdByAgentId: agent.id
    });
    const fork = await repository.createFork({
      id: "frk_1",
      projectId: project.id,
      parentForkId: null,
      owner: "agent-alpha",
      repo: "demo-fork",
      sourceOwner: "agenthub",
      sourceRepo: "demo",
      cloneUrl: pathToFileURL(bareRepo).toString(),
      goal: "Improve the project",
      status: "working",
      createdByAgentId: agent.id
    });
    await repository.createWorkJob({
      id: "job_1",
      agentId: agent.id,
      projectId: project.id,
      forkId: fork.id,
      status: "queued",
      identitySeed: 12345,
      prompt: "Inspect the repo and make one small useful change.",
      branch: "main",
      commitSha: null,
      result: null,
      error: null
    });

    const worker = new CodexGitWorker({
      repository,
      config: createWorkerConfig({
        giteaBaseUrl: pathToFileURL(remoteRoot).toString().replace(/\/$/, ""),
        workerWorkDir: join(temp, "worker"),
        codexBin: fakeCodex
      })
    });

    const result = await worker.runNext("test-worker");
    assert.equal(result?.job.status, "pushed");
    assert.ok(result?.job.commitSha);
    assert.deepEqual(result?.job.result?.changedFiles, ["worker-added.md"]);

    const checkout = join(temp, "checkout");
    await execFileAsync("git", ["clone", pathToFileURL(bareRepo).toString(), checkout]);
    assert.equal(await readFile(join(checkout, "worker-added.md"), "utf8"), "Generated by fake Codex\n");
    await assert.rejects(access(join(checkout, "codex-result.txt"), constants.F_OK));
    assert.equal(await worker.runNext("test-worker"), null);
  } finally {
    await rm(temp, { recursive: true, force: true });
  }
});

async function createBareRepoWithReadme(input: { bareRepo: string; temp: string }): Promise<void> {
  const seed = join(input.temp, "seed");
  await mkdir(seed, { recursive: true });
  await execFileAsync("git", ["init"], { cwd: seed });
  await execFileAsync("git", ["checkout", "-b", "main"], { cwd: seed });
  await execFileAsync("git", ["config", "user.name", "Test User"], { cwd: seed });
  await execFileAsync("git", ["config", "user.email", "test@example.com"], { cwd: seed });
  await writeFile(join(seed, "README.md"), "# Demo\n");
  await execFileAsync("git", ["add", "README.md"], { cwd: seed });
  await execFileAsync("git", ["commit", "-m", "Initial commit"], { cwd: seed });
  await mkdir(join(input.temp, "gitea", "agent-alpha"), { recursive: true });
  await execFileAsync("git", ["init", "--bare", input.bareRepo]);
  await execFileAsync("git", ["remote", "add", "origin", pathToFileURL(input.bareRepo).toString()], { cwd: seed });
  await execFileAsync("git", ["push", "origin", "main"], { cwd: seed });
}

function createWorkerConfig(input: { giteaBaseUrl: string; workerWorkDir: string; codexBin: string }): AppConfig {
  return {
    gitForge: "gitea",
    port: 0,
    databaseUrl: "",
    giteaBaseUrl: input.giteaBaseUrl,
    giteaToken: "test-token",
    giteaRootOwner: "agenthub",
    giteaRootOwnerType: "org",
    giteaSshUser: "git",
    giteaSshHost: "localhost",
    giteaSshPort: 22,
    giteaTlsSelfSigned: false,
    workerWorkDir: input.workerWorkDir,
    workerPollIntervalMs: 1,
    codexBin: input.codexBin,
    codexModel: null,
    codexTimeoutMs: 30000,
    codexDemoMode: true,
    codexTokenBudget: 1200,
    codexMaxChangedFiles: 1
  };
}
